name: styletransferml5
channels:
- intel
- defaults
dependencies:
- _tflow_select=2.3.0=mkl
- absl-py=0.7.0=py36_0
- astor=0.7.1=py36_0
- blas=1.0=mkl
- c-ares=1.15.0=h7b6447c_1
- gast=0.2.2=py36_0
- grpcio=1.14.1=py36h9ba97e2_0
- h5py=2.8.0=py36h989c5e5_3
- keras-applications=1.0.7=py_0
- keras-preprocessing=1.0.9=py_0
- libgcc-ng=8.2.0=hdf63c60_1
- libgfortran-ng=7.3.0=hdf63c60_0
- libprotobuf=3.6.1=hd408876_0
- libstdcxx-ng=8.2.0=hdf63c60_1
- markdown=3.0.1=py36_0
- mkl_fft=1.0.10=py36ha843d7b_0
- mkl_random=1.0.2=py36hd81dba3_0
- mock=2.0.0=py36_0
- numpy=1.16.2=py36h7e9f1db_0
- numpy-base=1.16.2=py36hde5b4d6_0
- pbr=5.1.3=py_0
- protobuf=3.6.1=py36he6710b0_0
- scipy=1.2.1=py36h7c811a0_0
- setuptools=27.2.0=py36_0
- tensorboard=1.12.2=py36he6710b0_0
- tensorflow-estimator=1.13.0=py_0
- tensorflow-mkl=1.13.1=h4fcabd2_0
- termcolor=1.1.0=py36_1
- bzip2=1.0.6=17
- hdf5=1.10.2=2
- intel-openmp=2019.3=intel_199
- intelpython=2019.3=0
- mkl=2019.3=intel_199
- openssl=1.0.2r=0
- pip=10.0.1=py36_0
- python=3.6.8=6
- six=1.11.0=py36_3
- sqlite=3.27.2=2
- tbb=2019.4=intel_199
- tcl=8.6.4=22
- tensorflow=1.13.1=py36_0
- tk=8.6.4=28
- werkzeug=0.14.1=py36_0
- wheel=0.31.0=py36_3
- xz=5.2.3=2
- zlib=1.2.11=5
- pip:
  - certifi==2019.3.9
  - chardet==3.0.4
  - decorator==4.4.0
  - idna==2.8
  - imageio==2.4.1
  - imageio-ffmpeg==0.2.0
  - intel-tensorflow==1.13.1
  - mkl-fft==1.0.10
  - mkl-random==1.0.2
  - moviepy==1.0.0
  - pillow==6.0.0
  - proglog==0.1.9
  - requests==2.21.0
  - tqdm==4.31.1
  - urllib3==1.24.1
prefix: /home/u24235/.conda/envs/styletransferml5

